import { supabase } from "@/integrations/supabase/client";

/**
 * Master catalog of transaction types that MUST each have at least one
 * active platform-scope row in `fee_structures`. This list mirrors
 * TRANSACTION_TYPES in CreateFeeStructureForm.tsx and locks against the
 * regressions found in docs/fee-management/e2e-audit-2026-05-31.md.
 */
export const REQUIRED_TRANSACTION_TYPES: string[] = [
  "transfer", "payment", "bill_payment",
  "mobile_money_transfer", "mobile_money_charge",
  "byo_mobile_money_routing", "byo_fallback_charge",
  "bank_transfer", "intra_bank_transfer", "inter_bank_transfer",
  "card_payment", "virtual_card_topup", "qr_payment",
  "card_issuance_fee", "card_maintenance_fee", "card_transaction_fee",
  "piggybank_deposit", "piggybank_withdrawal",
  "njangi_contribution", "njangi_payout",
  "rent_payment",
  "loan_disbursement", "loan_repayment", "loan_processing_fee",
  "savings_deposit", "savings_withdrawal",
  "international_transfer", "ussd_payment",
  "withdrawal", "account_funding",
  "gateway_charge", "gateway_payout",
  "paypal_payment", "fx_conversion", "escrow_payment",
  "api_request", "mobile_recharge", "invoice_create",
  "credit_report_purchase",
  "overdraft_fee", "overdraft_interest", "overdraft_setup_fee", "overdraft_renewal_fee",
  "atm_withdrawal", "standing_order", "dormancy_fee",
  "remittance_inbound", "remittance_outbound",
  "remittance_bank_credit", "remittance_wallet_credit",
  "remittance_bill_payment", "remittance_fx_markup",
  "travel_booking", "hotel_booking", "flight_booking", "tour_booking",
  "travel_cancellation_fee",
  "credit_score_inquiry", "credit_report_inquiry", "credit_premium_subscription",
  "statement_download_consumer", "statement_download_banking",
];

export interface AuditRow {
  transaction_type: string;
  covered: boolean;
  active_platform_rows: number;
  models: string[];
}

export interface AuditResult {
  ranAt: string;
  totalTypes: number;
  covered: number;
  missing: string[];
  rows: AuditRow[];
  pass: boolean;
}

export async function runFeeStructuresAudit(): Promise<AuditResult> {
  const { data, error } = await supabase
    .from("fee_structures")
    .select("transaction_type, fee_model, is_active, fee_scope, institution_id")
    .eq("is_active", true)
    .eq("fee_scope", "platform")
    .is("institution_id", null);

  if (error) throw error;

  const byType = new Map<string, { count: number; models: Set<string> }>();
  for (const row of data || []) {
    const t = row.transaction_type as string;
    const e = byType.get(t) ?? { count: 0, models: new Set<string>() };
    e.count += 1;
    if (row.fee_model) e.models.add(row.fee_model as string);
    byType.set(t, e);
  }

  const rows: AuditRow[] = REQUIRED_TRANSACTION_TYPES.map((t) => {
    const e = byType.get(t);
    return {
      transaction_type: t,
      covered: !!e && e.count > 0,
      active_platform_rows: e?.count ?? 0,
      models: e ? Array.from(e.models) : [],
    };
  });

  const missing = rows.filter((r) => !r.covered).map((r) => r.transaction_type);
  return {
    ranAt: new Date().toISOString(),
    totalTypes: REQUIRED_TRANSACTION_TYPES.length,
    covered: rows.length - missing.length,
    missing,
    rows,
    pass: missing.length === 0,
  };
}

export function buildAuditMarkdown(r: AuditResult): string {
  const status = r.pass ? "PASS" : "FAIL";
  const lines: string[] = [
    "# Fee Management — End-to-End Audit Report",
    "",
    `**Generated:** ${r.ranAt}`,
    `**Scope:** /admin/fee-management — every required transaction type`,
    `**Result:** **${status}** (${r.covered}/${r.totalTypes} transaction types covered)`,
    "",
    "## Summary",
    "",
    `- Required transaction types: **${r.totalTypes}**`,
    `- Covered (active platform row exists): **${r.covered}**`,
    `- Missing (no active platform row): **${r.missing.length}**`,
    "",
  ];

  if (r.missing.length) {
    lines.push("## Missing coverage");
    lines.push("");
    for (const m of r.missing) lines.push(`- \`${m}\``);
    lines.push("");
  }

  lines.push("## Coverage matrix");
  lines.push("");
  lines.push("| Transaction type | Covered | Active rows | Models |");
  lines.push("|---|---|---|---|");
  for (const row of r.rows) {
    lines.push(
      `| \`${row.transaction_type}\` | ${row.covered ? "yes" : "**no**"} | ${row.active_platform_rows} | ${row.models.join(", ") || "—"} |`,
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`Auto-generated by Fee Management → Run E2E Audit.`);
  return lines.join("\n");
}

export function downloadAuditReport(r: AuditResult) {
  const md = buildAuditMarkdown(r);
  const ts = r.ranAt.replace(/[:.]/g, "-");
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `fee-management-e2e-audit-${ts}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
