
INSERT INTO managed_email_types (email_key, category, name, description, default_subject, default_body_html, available_variables, trigger_event, is_system, is_active, sort_order) VALUES

-- CUSTOMER-FACING EMAILS
('withdrawal_approved', 'banking', 'Withdrawal Approved', 'Sent to customer when a withdrawal is approved and executed', 'Your Withdrawal Has Been Processed', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your withdrawal request of <strong>{{amount}} {{currency}}</strong> has been <strong>approved and executed</strong>.</p><ul><li><strong>Reference:</strong> {{reference}}</li><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Date:</strong> {{date}}</li></ul><p>The funds have been debited from your account. If you did not authorize this transaction, please contact your branch immediately.</p><p>Thank you for banking with <strong>{{institution_name}}</strong>.</p>', '["customer_name","amount","currency","reference","account_ref","date","institution_name"]', 'withdrawal.executed', true, true, 100),

('withdrawal_rejected', 'banking', 'Withdrawal Rejected', 'Sent to customer when a withdrawal request is rejected', 'Withdrawal Request Declined', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your withdrawal request of <strong>{{amount}} {{currency}}</strong> has been <strong>declined</strong>.</p><ul><li><strong>Reference:</strong> {{reference}}</li><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Reason:</strong> {{reason}}</li></ul><p>If you believe this decision was made in error, please visit your nearest branch or contact customer support.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","amount","currency","reference","account_ref","reason","institution_name"]', 'withdrawal.rejected', true, true, 101),

('withdrawal_pending_approval', 'banking', 'Withdrawal Pending', 'Sent to customer when their withdrawal requires manager approval', 'Withdrawal Request Received — Pending Approval', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your withdrawal request of <strong>{{amount}} {{currency}}</strong> has been received and is currently <strong>pending management approval</strong>.</p><ul><li><strong>Reference:</strong> {{reference}}</li><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Submitted:</strong> {{date}}</li></ul><p>You will receive a notification once your request has been reviewed. Processing typically takes 1–2 business hours.</p><p>Thank you for your patience,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","amount","currency","reference","account_ref","date","institution_name"]', 'withdrawal.pending', true, true, 102),

('withdrawal_expired', 'banking', 'Withdrawal Expired', 'Sent to customer when their withdrawal approval expires', 'Withdrawal Request Expired', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your withdrawal request of <strong>{{amount}} {{currency}}</strong> (Ref: <strong>{{reference}}</strong>) has <strong>expired</strong> without being processed within the approval window.</p><p>If you still wish to make this withdrawal, please submit a new request at your branch.</p><p>We apologize for any inconvenience,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","amount","currency","reference","institution_name"]', 'withdrawal.expired', true, true, 103),

('overdraft_eligible', 'banking', 'Overdraft Eligible', 'Sent to customer when their overdraft eligibility is confirmed', 'You Are Eligible for an Overdraft Facility', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Based on your account activity and financial profile, you are now <strong>eligible for an overdraft facility</strong>.</p><ul><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Recommended Limit:</strong> {{recommended_limit}} {{currency}}</li><li><strong>Risk Band:</strong> {{risk_band}}</li></ul><p>An overdraft gives you flexible access to additional funds when you need them. Visit your branch or contact us to activate your overdraft facility.</p><p>Best regards,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","account_ref","recommended_limit","currency","risk_band","institution_name"]', 'overdraft.eligible', true, true, 110),

('overdraft_approved', 'banking', 'Overdraft Approved', 'Sent to customer when their overdraft is approved', 'Your Overdraft Facility Has Been Approved', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your overdraft facility has been <strong>approved</strong> and is now active.</p><ul><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Approved Limit:</strong> {{approved_limit}} {{currency}}</li><li><strong>Available Amount:</strong> {{available_amount}} {{currency}}</li></ul><p>Please use your overdraft responsibly. Interest and fees may apply as per your agreement.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","account_ref","approved_limit","available_amount","currency","institution_name"]', 'overdraft.approved', true, true, 111),

('overdraft_suspended', 'banking', 'Overdraft Suspended', 'Sent to customer when their overdraft is suspended', 'Your Overdraft Facility Has Been Suspended', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your overdraft facility on account <strong>{{account_ref}}</strong> has been <strong>temporarily suspended</strong>.</p><ul><li><strong>Previous Limit:</strong> {{previous_limit}} {{currency}}</li><li><strong>Reason:</strong> {{reason}}</li></ul><p>During the suspension period, you will not be able to access overdraft funds. Please contact your branch to discuss reinstatement.</p><p>Regards,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","account_ref","previous_limit","currency","reason","institution_name"]', 'overdraft.suspended', true, true, 112),

('overdraft_revoked', 'banking', 'Overdraft Revoked', 'Sent to customer when their overdraft is revoked', 'Your Overdraft Facility Has Been Revoked', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your overdraft facility on account <strong>{{account_ref}}</strong> has been <strong>permanently revoked</strong>.</p><ul><li><strong>Previous Limit:</strong> {{previous_limit}} {{currency}}</li><li><strong>Reason:</strong> {{reason}}</li></ul><p>Any outstanding overdraft balance remains payable. Please contact your branch for repayment arrangements.</p><p>Regards,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","account_ref","previous_limit","currency","reason","institution_name"]', 'overdraft.revoked', true, true, 113),

('overdraft_reinstated', 'banking', 'Overdraft Reinstated', 'Sent to customer when their overdraft is reinstated', 'Your Overdraft Facility Has Been Reinstated', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your overdraft facility on account <strong>{{account_ref}}</strong> has been <strong>reinstated</strong>.</p><ul><li><strong>New Limit:</strong> {{new_limit}} {{currency}}</li><li><strong>Available Amount:</strong> {{available_amount}} {{currency}}</li></ul><p>Your overdraft is now active. Please continue to use it responsibly.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","account_ref","new_limit","available_amount","currency","institution_name"]', 'overdraft.reinstated', true, true, 114),

-- BANK MANAGEMENT EMAILS
('approval_pending_manager', 'banking_ops', 'Approval Pending (Manager)', 'Sent to managers when a withdrawal requires their approval', 'Action Required: Withdrawal Approval Pending', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>A withdrawal request requires your <strong>immediate approval</strong> as <strong>{{role_title}}</strong>.</p><ul><li><strong>Amount:</strong> {{amount}} {{currency}}</li><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Submitted By:</strong> {{submitted_by}}</li><li><strong>Branch:</strong> {{branch_name}}</li><li><strong>Reason:</strong> {{reason}}</li><li><strong>Reference:</strong> {{reference}}</li></ul><p>This request will <strong>expire in 24 hours</strong> if no action is taken.</p><p>Please log in to the Institution Portal to review and take action.</p><p>— <strong>{{institution_name}}</strong> Operations</p>', '["manager_name","role_title","amount","currency","account_ref","submitted_by","branch_name","reason","reference","institution_name"]', 'approval.pending', true, true, 200),

('approval_escalated', 'banking_ops', 'Approval Escalated', 'Sent to higher-authority managers when an approval is escalated', 'Approval Escalated to Your Authority', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>A withdrawal approval has been <strong>escalated</strong> to you as <strong>{{role_title}}</strong>.</p><ul><li><strong>Amount:</strong> {{amount}} {{currency}}</li><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Escalated From:</strong> {{from_role}}</li><li><strong>Reason:</strong> {{escalation_reason}}</li><li><strong>Reference:</strong> {{reference}}</li></ul><p>Please review and take action promptly.</p><p>— <strong>{{institution_name}}</strong> Operations</p>', '["manager_name","role_title","amount","currency","account_ref","from_role","escalation_reason","reference","institution_name"]', 'approval.escalated', true, true, 201),

('overdraft_review_required', 'banking_ops', 'Overdraft Review Required', 'Sent to branch managers when an overdraft requires manual review', 'Overdraft Application Requires Review', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>An overdraft application requires <strong>manual review and approval</strong>.</p><ul><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Customer:</strong> {{customer_name}}</li><li><strong>Recommended Limit:</strong> {{recommended_limit}} {{currency}}</li><li><strong>Risk Band:</strong> {{risk_band}}</li><li><strong>Score:</strong> {{score}}/100</li></ul><p>Please review the application in the Overdraft Management section of the Institution Portal.</p><p>— <strong>{{institution_name}}</strong> Operations</p>', '["manager_name","account_ref","customer_name","recommended_limit","currency","risk_band","score","institution_name"]', 'overdraft.review_required', true, true, 202),

('high_value_withdrawal_alert', 'banking_ops', 'High-Value Withdrawal Alert', 'Sent to senior management for high-value withdrawal audit trail', 'Alert: High-Value Withdrawal Processed', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>A <strong>high-value withdrawal</strong> has been processed at your institution.</p><ul><li><strong>Amount:</strong> {{amount}} {{currency}}</li><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Processed By:</strong> {{processed_by}}</li><li><strong>Branch:</strong> {{branch_name}}</li><li><strong>Approval:</strong> {{approval_status}}</li><li><strong>Reference:</strong> {{reference}}</li></ul><p>This alert is for your records and regulatory compliance.</p><p>— <strong>{{institution_name}}</strong> Risk &amp; Compliance</p>', '["manager_name","amount","currency","account_ref","processed_by","branch_name","approval_status","reference","institution_name"]', 'withdrawal.high_value', true, true, 203)

ON CONFLICT (email_key) DO NOTHING;
