
INSERT INTO managed_email_types (email_key, category, name, description, default_subject, default_body_html, available_variables, trigger_event, is_system, is_active, sort_order) VALUES

-- SAVINGS OPERATIONS
('savings_deposit_confirmed', 'transactional', 'Savings Deposit Confirmed', 'Sent when a deposit to savings account is confirmed', 'Savings Deposit Confirmed – {{currency}} {{amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your savings deposit of <strong>{{currency}} {{amount}}</strong> has been successfully credited.</p><ul><li><strong>Account:</strong> {{account_name}}</li><li><strong>New Balance:</strong> {{currency}} {{new_balance}}</li><li><strong>Reference:</strong> {{reference}}</li></ul><p>Keep saving — every deposit brings you closer to your goals!</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","amount","account_name","new_balance","reference","institution_name"]', 'savings.deposit', true, true, 50),

('savings_withdrawal_confirmed', 'transactional', 'Savings Withdrawal Confirmed', 'Sent when a savings withdrawal is processed', 'Savings Withdrawal Processed – {{currency}} {{amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your savings withdrawal of <strong>{{currency}} {{amount}}</strong> has been processed.</p><ul><li><strong>Account:</strong> {{account_name}}</li><li><strong>Remaining Balance:</strong> {{currency}} {{remaining_balance}}</li><li><strong>Reference:</strong> {{reference}}</li></ul><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","amount","account_name","remaining_balance","reference","institution_name"]', 'savings.withdrawal', true, true, 51),

('savings_goal_reached', 'transactional', 'Savings Goal Reached', 'Sent when customer reaches their savings target', '🎉 Congratulations! You Reached Your Savings Goal', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Amazing news! You have reached your savings target of <strong>{{currency}} {{target_amount}}</strong> in your <strong>{{account_name}}</strong> account.</p><ul><li><strong>Current Balance:</strong> {{currency}} {{current_balance}}</li><li><strong>Goal:</strong> {{currency}} {{target_amount}}</li></ul><p>Consider setting a new goal to keep your savings momentum going!</p><p>Congratulations,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","target_amount","account_name","current_balance","institution_name"]', 'savings.goal_reached', true, true, 52),

('savings_interest_credited', 'transactional', 'Interest Credited', 'Sent when interest is credited to savings account', 'Interest Credited to Your Savings Account', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Interest of <strong>{{currency}} {{interest_amount}}</strong> has been credited to your savings account.</p><ul><li><strong>Account:</strong> {{account_name}}</li><li><strong>Interest Rate:</strong> {{interest_rate}}% p.a.</li><li><strong>Period:</strong> {{period}}</li><li><strong>New Balance:</strong> {{currency}} {{new_balance}}</li></ul><p>Your money is working for you!</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","interest_amount","account_name","interest_rate","period","new_balance","institution_name"]', 'savings.interest', true, true, 53),

-- LOAN OPERATIONS
('loan_application_received', 'transactional', 'Loan Application Received', 'Sent when a loan application is submitted', 'Loan Application Received – {{application_number}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your loan application has been received and is being reviewed.</p><ul><li><strong>Application Number:</strong> {{application_number}}</li><li><strong>Requested Amount:</strong> {{currency}} {{requested_amount}}</li><li><strong>Tenure:</strong> {{tenure_months}} months</li><li><strong>Purpose:</strong> {{purpose}}</li></ul><p>You will be notified once a decision has been made. Review typically takes 1–3 business days.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","application_number","currency","requested_amount","tenure_months","purpose","institution_name"]', 'loan.applied', true, true, 60),

('loan_approved', 'transactional', 'Loan Approved', 'Sent when a loan application is approved', 'Your Loan Has Been Approved – {{currency}} {{approved_amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Congratulations! Your loan application has been <strong>approved</strong>.</p><ul><li><strong>Approved Amount:</strong> {{currency}} {{approved_amount}}</li><li><strong>Interest Rate:</strong> {{interest_rate}}%</li><li><strong>Monthly Payment:</strong> {{currency}} {{monthly_payment}}</li><li><strong>Tenure:</strong> {{tenure_months}} months</li><li><strong>Loan Account:</strong> {{loan_account_number}}</li></ul><p>Disbursement will be processed shortly. You will receive a confirmation once the funds are available.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","approved_amount","interest_rate","monthly_payment","tenure_months","loan_account_number","institution_name"]', 'loan.approved', true, true, 61),

('loan_disbursement_confirmed', 'transactional', 'Loan Disbursed', 'Sent when loan funds are disbursed', 'Loan Funds Disbursed – {{currency}} {{amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your loan of <strong>{{currency}} {{amount}}</strong> has been <strong>disbursed</strong> to your account.</p><ul><li><strong>Loan Account:</strong> {{loan_account_number}}</li><li><strong>First Payment Due:</strong> {{first_due_date}}</li><li><strong>Monthly Payment:</strong> {{currency}} {{monthly_payment}}</li></ul><p>Please ensure timely repayments to maintain a healthy credit profile.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","amount","loan_account_number","first_due_date","monthly_payment","institution_name"]', 'loan.disbursed', true, true, 62),

('loan_repayment_confirmed', 'transactional', 'Loan Repayment Received', 'Sent when a loan repayment is received', 'Loan Repayment Received – {{currency}} {{amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>We have received your loan repayment of <strong>{{currency}} {{amount}}</strong>.</p><ul><li><strong>Payment Reference:</strong> {{payment_reference}}</li><li><strong>Principal Paid:</strong> {{currency}} {{principal_paid}}</li><li><strong>Interest Paid:</strong> {{currency}} {{interest_paid}}</li><li><strong>Remaining Balance:</strong> {{currency}} {{remaining_balance}}</li><li><strong>Loan Status:</strong> {{loan_status}}</li></ul><p>On-time payments positively impact your credit score. Keep it up!</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","amount","payment_reference","principal_paid","interest_paid","remaining_balance","loan_status","institution_name"]', 'loan.repayment', true, true, 63),

('loan_overdue_alert', 'transactional', 'Loan Overdue Notice', 'Sent when a loan installment is overdue', 'Loan Payment Overdue – Immediate Action Required', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Your loan payment is now <strong>{{days_overdue}} days overdue</strong>.</p><ul><li><strong>Amount Due:</strong> {{currency}} {{amount_due}}</li><li><strong>Due Date:</strong> {{due_date}}</li><li><strong>Loan Account:</strong> {{loan_account_number}}</li><li><strong>Installment:</strong> #{{installment_number}}</li></ul><p>Late payments negatively affect your credit score. Please make your payment as soon as possible.</p><p>Contact your branch for assistance,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","days_overdue","currency","amount_due","due_date","loan_account_number","installment_number","institution_name"]', 'loan.overdue', true, true, 64),

('loan_completed', 'transactional', 'Loan Fully Repaid', 'Sent when a loan is fully repaid', '🎉 Loan Fully Repaid – Congratulations!', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>Congratulations! Your loan has been <strong>fully repaid</strong>.</p><ul><li><strong>Loan Account:</strong> {{loan_account_number}}</li><li><strong>Total Paid:</strong> {{currency}} {{total_paid}}</li></ul><p>Your excellent repayment history will positively reflect in your credit score. Thank you for banking with us!</p><p>Best regards,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","loan_account_number","currency","total_paid","institution_name"]', 'loan.completed', true, true, 65),

-- TELLER OPERATIONS
('teller_deposit_receipt', 'transactional', 'Teller Deposit Receipt', 'Sent to customer after a teller deposit', 'Deposit Confirmed – {{currency}} {{amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>A deposit of <strong>{{currency}} {{amount}}</strong> has been made to your account at the branch.</p><ul><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Balance Before:</strong> {{currency}} {{balance_before}}</li><li><strong>Balance After:</strong> {{currency}} {{balance_after}}</li><li><strong>Reference:</strong> {{reference}}</li><li><strong>Served By:</strong> {{teller_name}}</li><li><strong>Branch:</strong> {{branch_name}}</li></ul><p>Thank you for banking with <strong>{{institution_name}}</strong>.</p>', '["customer_name","currency","amount","account_ref","balance_before","balance_after","reference","teller_name","branch_name","institution_name"]', 'teller.deposit', true, true, 70),

('teller_withdrawal_receipt', 'transactional', 'Teller Withdrawal Receipt', 'Sent to customer after a teller withdrawal', 'Withdrawal Processed – {{currency}} {{amount}}', '<p>Dear <strong>{{customer_name}}</strong>,</p><p>A withdrawal of <strong>{{currency}} {{amount}}</strong> has been processed from your account at the branch.</p><ul><li><strong>Account:</strong> {{account_ref}}</li><li><strong>Balance Before:</strong> {{currency}} {{balance_before}}</li><li><strong>Balance After:</strong> {{currency}} {{balance_after}}</li><li><strong>Reference:</strong> {{reference}}</li><li><strong>Served By:</strong> {{teller_name}}</li><li><strong>Branch:</strong> {{branch_name}}</li></ul><p>If you did not authorize this transaction, please contact your branch immediately.</p><p>Thank you,<br/><strong>{{institution_name}}</strong></p>', '["customer_name","currency","amount","account_ref","balance_before","balance_after","reference","teller_name","branch_name","institution_name"]', 'teller.withdrawal', true, true, 71),

-- BANK MANAGEMENT
('loan_application_alert', 'banking_ops', 'New Loan Application Alert', 'Sent to loan officers when a new application is submitted', 'New Loan Application – {{currency}} {{requested_amount}}', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>A new loan application has been submitted for review.</p><ul><li><strong>Application:</strong> {{application_number}}</li><li><strong>Customer:</strong> {{customer_name}}</li><li><strong>Amount:</strong> {{currency}} {{requested_amount}}</li><li><strong>Tenure:</strong> {{tenure_months}} months</li><li><strong>Credit Score:</strong> {{credit_score}}</li><li><strong>Auto Decision:</strong> {{auto_decision}}</li></ul><p>Please review in the Loan Management section of the portal.</p><p>— <strong>{{institution_name}}</strong> Operations</p>', '["manager_name","application_number","customer_name","currency","requested_amount","tenure_months","credit_score","auto_decision","institution_name"]', 'loan.application_received', true, true, 210),

('loan_overdue_management_alert', 'banking_ops', 'Loan Overdue Management Alert', 'Sent to management when loans become overdue', 'Alert: {{overdue_count}} Loan Installments Now Overdue', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>The overdue detection system has identified <strong>{{overdue_count}} overdue loan installments</strong> affecting <strong>{{users_affected}} customers</strong>.</p><p>Please review the affected accounts in the Loan Management section and initiate appropriate follow-up actions.</p><p>Timely collections are critical for portfolio health.</p><p>— <strong>{{institution_name}}</strong> Risk Management</p>', '["manager_name","overdue_count","users_affected","institution_name"]', 'loan.overdue_batch', true, true, 211),

('daily_teller_summary', 'banking_ops', 'Daily Teller Activity Summary', 'Sent to branch managers with daily teller activity', 'Daily Branch Activity Summary – {{date}}', '<p>Dear <strong>{{manager_name}}</strong>,</p><p>Here is the daily activity summary for <strong>{{branch_name}}</strong> on <strong>{{date}}</strong>.</p><ul><li><strong>Total Deposits:</strong> {{currency}} {{total_deposits}} ({{deposit_count}} transactions)</li><li><strong>Total Withdrawals:</strong> {{currency}} {{total_withdrawals}} ({{withdrawal_count}} transactions)</li><li><strong>Net Position:</strong> {{currency}} {{net_position}}</li><li><strong>Pending Approvals:</strong> {{pending_approvals}}</li></ul><p>— <strong>{{institution_name}}</strong> Operations</p>', '["manager_name","branch_name","date","currency","total_deposits","deposit_count","total_withdrawals","withdrawal_count","net_position","pending_approvals","institution_name"]', 'teller.daily_summary', true, true, 212)

ON CONFLICT (email_key) DO NOTHING;
